routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// roocket.ir/admin

Route::namespace('Admin')->prefix('admin')->group(function (){
    $this->get('/panel' , 'PanelController@index');

    $this->resource('articles' , 'ArticleController');
});
//Route::resource('article')

app/Article.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use Sluggable;

     protected $guarded = [];
     protected $casts = [
       'images'=>'array'
     ];
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function path()
    {
        return "/article/$this->slug";
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function article()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Intervention\Image\Facades\Image;


class AdminController extends Controller
{
    protected function uploadImages($file)
    {
        $year = Carbon::now()->year;
        $imagePath = "/upload/images/{$year}/";
        $filename = $file->getClientOriginalName();

        $file = $file->move(public_path($imagePath) , $filename);

        $sizes = ["300" , "600" , "900"];
        $url['images'] = $this->resize($file->getRealPath() , $sizes , $imagePath , $filename);
        $url['thumb'] = $url['images'][$sizes[0]];

        return $url;
    }

    private function resize($path , $sizes , $imagePath , $filename)
    {
        $images['original'] = $imagePath . $filename;
        foreach ($sizes as $size) {
            $images[$size] = $imagePath . "{$size}_" . $filename;

            Image::make($path)->resize($size, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path($images[$size]));
        }

        return $images;
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Http\Requests\ArticleRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class ArticleController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::latest()->paginate(20);
        return view('Admin.articles.all', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        // $file = $request->input('images');
        $imagesUrl = $this->uploadImages($request->file('images'));

        auth()->user()->article()->create(array_merge($request->all(), ['images'=>$imagesUrl]));

        return redirect(route('articles.index'));
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('Admin.articles.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, Article $article)
    {
         $file = $request->file('images');
         $inputs =  $request->all();

         if ($file) {
           $inputs['images'] = $this->uploadImages($request->file('images'));
         }else{
           $inputs['images'] = $articles->images;
           $inputs['images']['thumb'] = $inputs['imagesThumb'];
         }


         unset($inputs['imagesThumb']);
         $article->update($inputs);
         return redirect(route('articles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect(route('articles.index'));
    }
}

app/Http/Controllers/Admin/PanelController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PanelController extends Controller
{
    public function index()
    {
        return view('Admin.panel');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/Admin/articles/all.blade.php
@extends('Admin.master')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
          <h2>articles list</h2>
          <a href="{{ route('articles.create') }}" class="btn btn-small btn-primary">send article</a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>عنوان مقاله</th>
                    <th>تعداد نظرات</th>
                    <th>تعداد بازدید</th>
                    <th>عملیات </th>
                </tr>
                </thead>
                <tbody>
                  @foreach($articles as $article)
                    <tr>
                        <td><a href="{{ $article->path() }}">{{ $article->title }}</a></td>
                        <td>{{ $article->commentCount }}</td>
                        <td>{{ $article->viewCount }}</td>
                        <td>
                          <form action="{{ route('articles.destroy', ['id'=>$article->id]) }}" method="post">
                              {{ method_field('delete') }}
                              {{ csrf_field() }}
                              <div class="btn-group btn-group-xs">
                                  <a href="{{ route('articles.edit', ['id'=>$article->id]) }}" class="btn btn-primary">edit</a>
                                  <button type="submit" class="btn btn-danger">delete</button>
                              </div>
                          </form>
                        </td>
                    </tr>
                  @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/Admin/articles/create.blade.php
@extends('Admin.master')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
          <h2>create article</h2>
        </div>
        <div class="table-responsive">
            @include('Admin.section.errors')
            <form class="form-horizontal" style="padding: 20px;" action="{{ route('articles.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="col-sm-12">
                  <div class="form-groupe">
                      <label for="title" class="control-label">subject</label>
                      <input type="text" class="form-control" name="title" value="{{ old('title') }}" id="title" placeholder="enter article subject">
                  </div>
              </div>

                <div class="col-sm-12">
                  <div class="form-groupe">
                      <label for="description" class="control-label">description</label>
                      <textarea type="text" class="form-control" name="description" id="description" placeholder="enter article description" rows="5">{{ old('description') }}</textarea>
                  </div>
              </div>

                <div class="col-sm-12">
                  <div class="form-groupe">
                      <label for="body" class="control-label">body</label>
                      <textarea rows="5" class="form-control" name="body"  id="body" placeholder="enter article body">{{ old('body') }} </textarea>
                  </div>
              </div>

                <div class="form-group">
                  <div class="col-sm-6">
                      <div class="col-sm-12">
                        <div class="form-groupe">
                            <label for="images" class="control-label">images</label>
                            <input type="file" class="form-control" name="images" id="images" placeholder="enter article images">
                        </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                      <div class="col-sm-12">
                        <div class="form-groupe">
                            <label for="tags" class="control-label">tags</label>
                            <input type="text" class="form-control" name="tags" id="tags" placeholder="enter article tags" value="{{ old('tags') }}">
                        </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary">send information</button>
                    <!-- <button type="submit" class="btn btn-danger">ارسال</button> -->
                  </div>

                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/Admin/articles/edit.blade.php
@extends('Admin.master')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
          <h2>edit article</h2>
        </div>
        <div class="table-responsive">
            @include('Admin.section.errors')
            <form class="form-horizontal" style="padding: 20px;" action="{{ route('articles.update', ['id'=>$article->id] ) }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="col-sm-12">
                  <div class="form-groupe">
                      <label for="title" class="control-label">subject</label>
                      <input type="text" class="form-control" name="title" value="{{ $article->title }}" id="title" placeholder="enter article subject">
                  </div>
              </div>

                <div class="col-sm-12">
                  <div class="form-groupe">
                      <label for="description" class="control-label">description</label>
                      <textarea type="text" class="form-control" name="description" id="description" placeholder="enter article description" rows="5">{{ $article->description }}</textarea>
                  </div>
              </div>

                <div class="col-sm-12">
                  <div class="form-groupe">
                      <label for="body" class="control-label">body</label>
                      <textarea rows="5" class="form-control" name="body"  id="body" placeholder="enter article body">{{ $article->body }}</textarea>
                  </div>
              </div>

                <div class="form-group">
                  <div class="col-sm-12">
                      <div class="col-sm-12">
                        <div class="form-groupe">
                            <label for="images" class="control-label">images</label>
                            <input type="file" class="form-control" name="images" id="images" placeholder="enter article images">
                        </div>
                    </div>
                  </div>
                  <div class="col-sm-12">
                      <div class="row">
                          @foreach ($article->images['images'] as $key => $image)
                              <div class="col-sm-2">
                                  <label class="control-label">
                                    {{ $key }}
                                    <input type="radio" name="imagesThumb" value="{{ $image }}" {{ $article->images['thumb']== $image ? 'checked' : ''}}>
                                    <a href="{{ $image }}"> <img src="{{ $image }}" width="100%"></a>
                                  </label>
                              </div>
                          @endforeach
                      </div>
                  </div>
                </div>
                <div class="form-group">

                  <div class="col-sm-6">
                      <div class="col-sm-12">
                        <div class="form-groupe">
                            <label for="tags" class="control-label">tags</label>
                            <input type="text" class="form-control" name="tags" value="{{ $article->tags }}" id="tags" placeholder="enter article tags">
                        </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary">send information</button>
                    <!-- <button type="submit" class="btn btn-danger">ارسال</button> -->
                  </div>

                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/Admin/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>وبسایت آموزشی لاراول</title>

    <link rel="stylesheet" href="/css/admin.css">
</head>

<body>

    @include('Admin.section.header')
        @yield('content')
    @include('Admin.section.footer')
</body>
</html>

resources/views/Admin/panel.blade.php
@extends('Admin.master')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Dashboard</h1>

        <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
        </div>

        <h2 class="sub-header">Section title</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Header</th>
                    <th>Header</th>
                    <th>Header</th>
                    <th>Header</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1,001</td>
                    <td>Lorem</td>
                    <td>ipsum</td>
                    <td>dolor</td>
                    <td>sit</td>
                </tr>
                <tr>
                    <td>1,002</td>
                    <td>amet</td>
                    <td>consectetur</td>
                    <td>adipiscing</td>
                    <td>elit</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>Integer</td>
                    <td>nec</td>
                    <td>odio</td>
                    <td>Praesent</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>libero</td>
                    <td>Sed</td>
                    <td>cursus</td>
                    <td>ante</td>
                </tr>
                <tr>
                    <td>1,004</td>
                    <td>dapibus</td>
                    <td>diam</td>
                    <td>Sed</td>
                    <td>nisi</td>
                </tr>
                <tr>
                    <td>1,005</td>
                    <td>Nulla</td>
                    <td>quis</td>
                    <td>sem</td>
                    <td>at</td>
                </tr>
                <tr>
                    <td>1,006</td>
                    <td>nibh</td>
                    <td>elementum</td>
                    <td>imperdiet</td>
                    <td>Duis</td>
                </tr>
                <tr>
                    <td>1,007</td>
                    <td>sagittis</td>
                    <td>ipsum</td>
                    <td>Praesent</td>
                    <td>mauris</td>
                </tr>
                <tr>
                    <td>1,008</td>
                    <td>Fusce</td>
                    <td>nec</td>
                    <td>tellus</td>
                    <td>sed</td>
                </tr>
                <tr>
                    <td>1,009</td>
                    <td>augue</td>
                    <td>semper</td>
                    <td>porta</td>
                    <td>Mauris</td>
                </tr>
                <tr>
                    <td>1,010</td>
                    <td>massa</td>
                    <td>Vestibulum</td>
                    <td>lacinia</td>
                    <td>arcu</td>
                </tr>
                <tr>
                    <td>1,011</td>
                    <td>eget</td>
                    <td>nulla</td>
                    <td>Class</td>
                    <td>aptent</td>
                </tr>
                <tr>
                    <td>1,012</td>
                    <td>taciti</td>
                    <td>sociosqu</td>
                    <td>ad</td>
                    <td>litora</td>
                </tr>
                <tr>
                    <td>1,013</td>
                    <td>torquent</td>
                    <td>per</td>
                    <td>conubia</td>
                    <td>nostra</td>
                </tr>
                <tr>
                    <td>1,014</td>
                    <td>per</td>
                    <td>inceptos</td>
                    <td>himenaeos</td>
                    <td>Curabitur</td>
                </tr>
                <tr>
                    <td>1,015</td>
                    <td>sodales</td>
                    <td>ligula</td>
                    <td>in</td>
                    <td>libero</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/Admin/section/errors.blade.php
@if(count($errors) > 0)
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

resources/views/Admin/section/footer.blade.php
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/admin.js"></script>

resources/views/Admin/section/header.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">وبسایت آموزشی لاراول</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            {{--<ul class="nav navbar-nav navbar-right">--}}
                {{--<li><a href="#">Dashboard</a></li>--}}
                {{--<li><a href="#">Settings</a></li>--}}
                {{--<li><a href="#">Profile</a></li>--}}
                {{--<li><a href="#">Help</a></li>--}}
            {{--</ul>--}}
            {{--<form class="navbar-form navbar-right">--}}
                {{--<input type="text" class="form-control" placeholder="Search...">--}}
            {{--</form>--}}

            <div class="navbar-left">
                <a href="/logout" class="btn btn-sm btn-warning" style="margin: 15px">خروج از پنل کاربری</a>
            </div>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="/admin/panel">پنل اصلی</a></li>
                <li><a href="/admin/articles">مقاله ها</a></li>
                <li><a href="/admin/courses">دوره ها</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">کاربران <span class="badge">0</span></a></li>
                <li><a href="">پرداختی های موفق <span class="badge">0</span></a></li>
                <li><a href="">پرداختی های ناموفق <span class="badge">0</span></a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">همه نظرات</a></li>
                <li><a href="">نظرات تایید نشده <span class="badge">0</span></a></li>
                {{--<li><a href="">Another nav item</a></li>--}}
            </ul>
        </div>